const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Dinnn',
    introDesc: `Hong biết nà em bé còn zận emm hongggg taaaa`,
    btnIntro: 'Aluu babyy',
    title: 'Mỏninnnn bé iuuu 🥰',
    desc: 'Bé có iu em honggg ',
    btnYes: 'iuuu nắmm nunn 💞',
    btnNo: 'hok iuu 😡',
    question: 'Chọn iuu em zayy thì bé đừn zận nựaaa nkaaa 🥺',
    btnReply: 'Gửi cho emm',
    reply: 'đượt ruii anh hok zận emm nữa, anh iu emm baby ❤️',
    mess: 'aww 🥰 iuu em bé nắmmmm 😘😘',
    messDesc: 'Em yêu anh ❤️',
